allowBuilds:
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@supabase/cli-darwin-arm64@2.113.0'
  - '@supabase/cli-darwin-x64@2.113.0'
  - '@supabase/cli-linux-arm64-musl@2.113.0'
  - '@supabase/cli-linux-arm64@2.113.0'
  - '@supabase/cli-linux-x64-musl@2.113.0'
  - '@supabase/cli-linux-x64@2.113.0'
  - '@supabase/cli-windows-arm64@2.113.0'
  - '@supabase/cli-windows-x64@2.113.0'
  - supabase@2.113.0
